<?php
namespace App\Controllers\Admin;
use App\Controllers\Controller; use App\Database;
final class PostController extends Controller {
 private function db(){ $pdo=Database::connection(); if(!$pdo){flash('error','قاعدة البيانات غير متصلة.');redirect('/admin');} return $pdo; }
 public function index():void{$pdo=$this->db();$posts=$pdo->query('SELECT * FROM posts ORDER BY created_at DESC')->fetchAll();$this->adminView('admin/posts/index',['title'=>'إدارة المقالات','posts'=>$posts]);}
 public function create():void{$this->adminView('admin/posts/form',['title'=>'مقال جديد','post'=>null]);}
 public function store():void{verify_csrf();$pdo=$this->db();$title=trim((string)($_POST['title']??''));if($title===''){flash('error','عنوان المقال مطلوب.');redirect('/admin/posts/create');}$slug=trim((string)($_POST['slug']??''))?:slugify($title);$st=$pdo->prepare("INSERT INTO posts(title,slug,excerpt,content,featured_image,meta_title,meta_description,canonical_url,status,published_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())");$st->execute([$title,$slug,$_POST['excerpt']??null,$_POST['content']??'',$_POST['featured_image']??null,$_POST['meta_title']??null,$_POST['meta_description']??null,$_POST['canonical_url']??null,$_POST['status']??'draft',($_POST['status']??'draft')==='published'?date('Y-m-d H:i:s'):null]);flash('success','تم إنشاء المقال.');redirect('/admin/posts');}
 public function edit(string $id):void{$pdo=$this->db();$st=$pdo->prepare('SELECT * FROM posts WHERE id=?');$st->execute([(int)$id]);$post=$st->fetch();if(!$post)redirect('/admin/posts');$this->adminView('admin/posts/form',['title'=>'تعديل المقال','post'=>$post]);}
 public function update(string $id):void{verify_csrf();$pdo=$this->db();$title=trim((string)($_POST['title']??''));$slug=trim((string)($_POST['slug']??''))?:slugify($title);$status=in_array($_POST['status']??'draft',['draft','published'],true)?$_POST['status']:'draft';$st=$pdo->prepare("UPDATE posts SET title=?,slug=?,excerpt=?,content=?,featured_image=?,meta_title=?,meta_description=?,canonical_url=?,status=?,published_at=CASE WHEN ?='published' THEN COALESCE(published_at,NOW()) ELSE published_at END,updated_at=NOW() WHERE id=?");$st->execute([$title,$slug,$_POST['excerpt']??null,$_POST['content']??'',$_POST['featured_image']??null,$_POST['meta_title']??null,$_POST['meta_description']??null,$_POST['canonical_url']??null,$status,$status,(int)$id]);flash('success','تم تحديث المقال.');redirect('/admin/posts');}
 public function delete(string $id):void{verify_csrf();$pdo=$this->db();$pdo->prepare('DELETE FROM posts WHERE id=?')->execute([(int)$id]);flash('success','تم حذف المقال.');redirect('/admin/posts');}
}