<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
set_exception_handler(function(Throwable $error):void{fwrite(STDERR,$error->getMessage()."\n");exit(1);});
$base=getenv('TEST_BASE_URL')?:'http://127.0.0.1:8081';
$db=(string)env('DB_DATABASE','');
if(!preg_match('#^http://127\\.0\\.0\\.1:\\d+$#',$base)||!str_ends_with($db,'_test')){fwrite(STDERR,"Tests require a loopback server and database name ending in _test.\n");exit(1);}
$pdo=App\Database::connection();if(!$pdo)exit("Test MySQL unavailable\n");
if(!str_contains(str_replace('\\','/',storage_path()),'/storage/testing/'))exit("Tests require isolated storage/testing runtime\n");
foreach(glob(storage_path('cache/rate-limits/*.json'))?:[] as $bucket)unlink($bucket);
$pdo->exec(file_get_contents(base_path('database/schema.sql')));
$argv=['migrate.php','--backup-confirmed'];require base_path('database/migrate.php');require base_path('database/migrate.php');
$pdo->exec('DELETE FROM tracking_events');$pdo->exec('DELETE FROM leads');$pdo->exec('DELETE FROM posts');$pdo->exec('DELETE FROM users');
$password=bin2hex(random_bytes(16));$email='qa@example.invalid';
$pdo->prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'admin')")->execute(['QA',$email,password_hash($password,PASSWORD_DEFAULT)]);
$pdo->prepare("INSERT INTO posts(title,slug,excerpt,content,status,published_at) VALUES(?,?,?,?,?,?)")->execute(['مقال اختبار','qa-article','مقتطف اختبار','<p>آمن</p><script>alert(1)</script><img src=x onerror=alert(1)>','published',date('Y-m-d H:i:s')]);
$existingPostId=(int)$pdo->lastInsertId();
$jar=tempnam(sys_get_temp_dir(),'sd-qa-');$count=0;
register_shutdown_function(function()use($jar){if(is_file($jar))unlink($jar);});
function check(bool $condition,string $label):void{global $count;if(!$condition)throw new RuntimeException('FAILED: '.$label);$count++;echo "PASS $label\n";}
function request(string $path,string $method='GET',?array $data=null,?string $raw=null,?string $contentType=null):array{
 global $base,$jar;
 $curl=curl_init($base.$path);$headers=[];
 curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEJAR=>$jar,CURLOPT_COOKIEFILE=>$jar,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_TIMEOUT=>15,CURLOPT_HEADERFUNCTION=>function($curl,$line)use(&$headers){$parts=explode(':',$line,2);if(count($parts)===2)$headers[strtolower(trim($parts[0]))]=trim($parts[1]);return strlen($line);}]);
 if($data!==null)curl_setopt($curl,CURLOPT_POSTFIELDS,http_build_query($data));
 if($raw!==null)curl_setopt($curl,CURLOPT_POSTFIELDS,$raw);
 if($contentType)curl_setopt($curl,CURLOPT_HTTPHEADER,['Content-Type: '.$contentType]);
 $body=curl_exec($curl);if($body===false)throw new RuntimeException(curl_error($curl));
 $status=curl_getinfo($curl,CURLINFO_RESPONSE_CODE);curl_close($curl);return compact('status','body','headers');
}
function field(string $body,string $name):string{preg_match('/name="'.preg_quote($name,'/').'" value="([^"]+)"/',$body,$m);return html_entity_decode($m[1]??'',ENT_QUOTES,'UTF-8');}
function context(string $body):array{preg_match('/<script[^>]*id="sd-context"[^>]*>(.*?)<\\/script>/s',$body,$m);return json_decode($m[1]??'{}',true)?:[];}
foreach(['/','/services/web-development','/services/digital-marketing','/services/seo','/services/graphic-design','/services/classified-ads','/services/custom-software','/blog','/blog/qa-article','/privacy','/terms','/admin/login','/assets/css/app.css','/assets/css/admin.css','/assets/js/app.js','/assets/img/logo-sorouh-digital.png','/robots.txt','/sitemap.xml'] as $path){
 $r=request($path);check($r['status']===200,'GET '.$path);check(!preg_match('/Warning:|Fatal error:/',$r['body']),'no PHP errors '.$path);
}
check(request('/services/custom-solutions')['status']===301,'legacy service redirect');
check(request('/blog/')['status']===301,'trailing slash redirect');
foreach(['/missing','/services/missing','/blog/missing','/app/bootstrap.php'] as $path)check(request($path)['status']===404,'404 '.$path);
check(in_array(request('/.env')['status'],[403,404],true),'environment file inaccessible');
check(request('/blog','POST',[])['status']===405,'method mismatch');
foreach(['/admin','/admin/posts','/admin/posts/create','/admin/posts/1/edit','/admin/leads','/admin/analytics'] as $path)check(request($path)['status']===302,'anonymous denied '.$path);
foreach(['/admin/posts','/admin/posts/1/update','/admin/posts/1/delete','/admin/leads/1/status'] as $path)check(request($path,'POST',['title'=>'exploit'])['status']===302,'anonymous mutation denied '.$path);
check((int)$pdo->query('SELECT COUNT(*) FROM posts')->fetchColumn()===1,'anonymous writes did not change posts');
check(request('/contact','POST',[])['status']===403,'missing CSRF rejected');
check(request('/contact','POST',['_token'=>['bad']])['status']===403,'array CSRF rejected');
$landing=request('/?utm_source=haraj&utm_medium=classified&utm_campaign=web_design&utm_content=ad_01&utm_term=site&email=private');
$ctx=context($landing['body']);check($ctx['attribution']['utm_source']==='haraj','landing UTM captured');
$next=request('/services/seo');check(context($next['body'])['attribution']['utm_campaign']==='web_design','UTM survives navigation');
check(context($next['body'])['attribution']['landing_page']==='/','original landing retained without query data');
check(!str_contains(json_encode(context($next['body'])['attribution']),'private'),'sensitive query omitted');
$home=request('/');$token=field($home['body'],'_token');$submission=field($home['body'],'submission_id');
sleep(2);
$form=['_token'=>$token,'submission_id'=>$submission,'name'=>'عميل اختبار','phone'=>'0551234567','email'=>'qa@example.invalid','service'=>'تصميم وبرمجة موقع','message'=>'طلب تجريبي','consent'=>'1'];
$invalid=$form;$invalid['email']='bad';check(request('/contact','POST',$invalid)['status']===302,'invalid email handled');
check((int)$pdo->query('SELECT COUNT(*) FROM leads')->fetchColumn()===0,'invalid email not persisted');
$invalid=$form;unset($invalid['consent']);request('/contact','POST',$invalid);
check((int)$pdo->query('SELECT COUNT(*) FROM leads')->fetchColumn()===0,'consent required');
$invalid=$form;$invalid['website']='spam';check(request('/contact','POST',$invalid)['status']===422,'honeypot rejected');
check(request('/contact','POST',$form)['status']===302,'valid lead submitted');
$lead=$pdo->query('SELECT * FROM leads LIMIT 1')->fetch();
check($lead['utm_source']==='haraj'&&$lead['utm_content']==='ad_01'&&$lead['utm_term']==='site','lead attribution persisted');
check(preg_match('/^SD-[0-9]{6}-[A-F0-9]{6}$/',$lead['lead_id'])===1,'readable lead ID');
check($lead['visitor_id']!==''&&$lead['session_id']!=='','lead linked to visitor/session');
check(!empty($lead['consent_at']),'consent time recorded');
check((int)$pdo->query("SELECT COUNT(*) FROM tracking_events WHERE event_name='form_submit'")->fetchColumn()===1,'confirmed conversion persisted');
request('/contact','POST',$form);check((int)$pdo->query('SELECT COUNT(*) FROM leads')->fetchColumn()===1,'duplicate submit idempotent');
$success=request('/');check(context($success['body'])['conversion']===true,'confirmed external conversion context');
check(context(request('/')['body'])['conversion']===false,'conversion not repeated on refresh');
$trackToken=context($success['body'])['token'];
foreach(['page_view','whatsapp_click','phone_click','form_start','cta_click','service_view'] as $event)check(request('/api/track','POST',null,json_encode(['_token'=>$trackToken,'event'=>$event,'page'=>'/services/seo?phone=private','meta'=>['email'=>'private']]),'application/json')['status']===200,'tracking '.$event);
check(request('/api/track','POST',null,'{','application/json')['status']===400,'malformed JSON rejected');
check(request('/api/track','POST',null,'[]','text/plain')['status']===415,'wrong media type rejected');
check(request('/api/track','POST',null,json_encode(['event'=>'page_view']),'application/json')['status']===403,'track CSRF required');
check(request('/api/track','POST',null,json_encode(['_token'=>$trackToken,'event'=>'form_submit']),'application/json')['status']===422,'client cannot fabricate conversion');
check(request('/api/track','POST',null,str_repeat('x',8200),'application/json')['status']===413,'oversized tracking rejected');
check((int)$pdo->query("SELECT COUNT(*) FROM tracking_events WHERE metadata LIKE '%private%' OR page_url LIKE '%private%'")->fetchColumn()===0,'tracking drops personal metadata and query');
$article=request('/blog/qa-article');check(!str_contains($article['body'],'alert(1)')&&!str_contains($article['body'],'onerror='),'legacy article HTML sanitized');
$login=request('/admin/login');$before=$login['headers']['set-cookie']??'';
$token=field($login['body'],'_token');
check(request('/admin/login','POST',['_token'=>$token,'email'=>$email,'password'=>'incorrect'])['status']===302,'wrong password rejected');
check(request('/admin')['status']===302,'wrong password does not authenticate');
$login=request('/admin/login');$token=field($login['body'],'_token');
$authenticated=request('/admin/login','POST',['_token'=>$token,'email'=>$email,'password'=>$password]);
check($authenticated['status']===302&&$authenticated['headers']['location']==='/admin','admin login');
check(str_contains($authenticated['headers']['set-cookie']??'','HttpOnly')&&str_contains($authenticated['headers']['set-cookie']??'','SameSite=Lax'),'session cookie flags');
foreach(['/admin','/admin/posts','/admin/posts/create','/admin/posts/'.$existingPostId.'/edit','/admin/leads','/admin/analytics'] as $path)check(request($path)['status']===200,'authenticated '.$path);
$admin=request('/admin');$adminToken=field($admin['body'],'_token');
check($adminToken!==$token,'CSRF rotated on login');
check(($admin['headers']['cache-control']??'')==='no-store','admin not cached');
check(request('/admin/posts','POST',['_token'=>$token])['status']===403,'old CSRF invalidated');
$post=['_token'=>$adminToken,'title'=>'عنوان جديد','slug'=>'new-article','content'=>'<p>نص</p><img src="https://example.com/a.jpg" onerror="alert(1)"><script>alert(1)</script>','status'=>'draft'];
request('/admin/posts','POST',$post);$postId=(int)$pdo->query("SELECT id FROM posts WHERE slug='new-article'")->fetchColumn();check($postId>0,'post created');
check(!str_contains($pdo->query("SELECT content FROM posts WHERE id=$postId")->fetchColumn(),'onerror'),'stored HTML safe');
request('/admin/posts','POST',$post);check((int)$pdo->query("SELECT COUNT(*) FROM posts WHERE slug='new-article'")->fetchColumn()===1,'duplicate slug handled');
$post['status']='published';request('/admin/posts/'.$postId.'/update','POST',$post);check(request('/blog/new-article')['status']===200,'post published and readable');
check(str_contains(request('/sitemap.xml')['body'],'/blog/new-article'),'published article in sitemap');
request('/admin/leads/'.$lead['id'].'/status','POST',['_token'=>$adminToken,'status'=>'contacted']);
check($pdo->query('SELECT status FROM leads LIMIT 1')->fetchColumn()==='contacted','CRM status update');
request('/admin/posts/'.$postId.'/delete','POST',['_token'=>$adminToken]);check(request('/blog/new-article')['status']===404,'post deleted');
$pdo->exec('UPDATE users SET is_active=0');check(request('/admin')['status']===302,'disabled admin denied immediately');
$pdo->exec('UPDATE users SET is_active=1');check(request('/admin')['status']===302,'disabled session permanently revoked');
$login=request('/admin/login');$token=field($login['body'],'_token');request('/admin/login','POST',['_token'=>$token,'email'=>$email,'password'=>$password]);
$adminToken=field(request('/admin')['body'],'_token');
$savedHash=$pdo->query('SELECT password_hash FROM users LIMIT 1')->fetchColumn();
$pdo->prepare('UPDATE users SET password_hash=?')->execute([password_hash(bin2hex(random_bytes(16)),PASSWORD_DEFAULT)]);
check(request('/admin')['status']===302,'password reset revokes active sessions');
$pdo->prepare('UPDATE users SET password_hash=?')->execute([$savedHash]);
$login=request('/admin/login');$token=field($login['body'],'_token');request('/admin/login','POST',['_token'=>$token,'email'=>$email,'password'=>$password]);
$adminToken=field(request('/admin')['body'],'_token');
request('/admin/logout','POST',['_token'=>$adminToken]);check(request('/admin')['status']===302,'logout revoked authorization');
$login=request('/admin/login');$token=field($login['body'],'_token');
for($i=0;$i<8;$i++)$limited=request('/admin/login','POST',['_token'=>$token,'email'=>$email,'password'=>'wrong']);
check($limited['status']===429,'login rate limit enforced');
check(!str_contains(App\Html::sanitize('<a href="javascript:alert(1)">x</a><svg onload="alert(1)"></svg>'),'javascript:'),'unsafe URL blocked');
check(App\RateLimiter::allow('unit-'.bin2hex(random_bytes(8)),1,60),'limiter fresh bucket');
$pdo->exec('RENAME TABLE posts TO posts_test_unavailable');
try{$failure=request('/');check($failure['status']===500,'unexpected database error returns 500');check(!str_contains($failure['body'],'SQLSTATE')&&!str_contains($failure['body'],'Stack trace'),'production error details hidden');check(($failure['headers']['x-robots-tag']??'')==='noindex, nofollow','error response noindex');}finally{$pdo->exec('RENAME TABLE posts_test_unavailable TO posts');}
check(str_contains(request('/services/seo')['body'],'application/ld+json'),'service structured data present');
check(str_contains(request('/robots.txt')['body'],'Disallow: /'),'local robots disallows indexing');
check(str_contains(request('/')['headers']['content-security-policy']??'',"object-src 'none'"),'CSP enforced');
echo "ALL $count CHECKS PASSED\n";
